version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install virtualenv
      - python3 -m venv test_venv
      - . test_venv/bin/activate
      - pip install --upgrade pip
      - pip install -r src/requirements.txt
      - rm -rf dspt
      - apt-get update
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y ant 
      - apt-get clean
      - apt-get update 
      - apt-get install ca-certificates-java 
      - apt-get clean 
      - update-ca-certificates 

      
  build:
    commands:
      - python3 src/myIP.py 
  post_build:
    commands:
      - echo Build completed on `date`
